FROM mysql:latest as build

ENV MYSQL_ROOT_PASSWORD=root
ENV MYSQL_DATABASE=mydatabase
ENV MYSQL_USER=myuser
ENV MYSQL_PASSWORD=mypassword

FROM mysql:latest

COPY --from=build /var/lib/mysql /var/lib/mysql

EXPOSE 3306

CMD ["mysqld"]
